# Generated by Django 3.2.25 on 2024-04-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20240413_1253'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='answerlike',
            name='unique_answerlike_user',
        ),
        migrations.RemoveConstraint(
            model_name='questionlike',
            name='unique_questionlike_user',
        ),
        migrations.AddConstraint(
            model_name='answerlike',
            constraint=models.UniqueConstraint(fields=('user', 'answer'), name='unique_answerlike_user'),
        ),
        migrations.AddConstraint(
            model_name='questionlike',
            constraint=models.UniqueConstraint(fields=('user', 'question'), name='unique_questionlike_user'),
        ),
    ]
