# Generated by Django 3.2.25 on 2024-04-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_question_like_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='like_count',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(to='app.Tag'),
        ),
    ]
