# Generated by Django 3.2.25 on 2024-05-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20240520_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='static/img/avatar_one.jpg', null=True, upload_to='images'),
        ),
    ]
